"""empty message

Revision ID: 2f774d697077
Revises: 949929045eff
Create Date: 2024-06-30 16:12:36.922907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f774d697077'
down_revision: Union[str, None] = '949929045eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrices', sa.Column('matrices', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matrices', sa.Column('matrix_telegram_usernames', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_matrices_matrices'), 'matrices', ['matrices'], unique=False)
    op.create_index(op.f('ix_matrices_matrix_telegram_usernames'), 'matrices', ['matrix_telegram_usernames'], unique=False)
    op.drop_column('matrices', 'telegram_users_positions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrices', sa.Column('telegram_users_positions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_matrices_matrix_telegram_usernames'), table_name='matrices')
    op.drop_index(op.f('ix_matrices_matrices'), table_name='matrices')
    op.drop_column('matrices', 'matrix_telegram_usernames')
    op.drop_column('matrices', 'matrices')
    # ### end Alembic commands ###
