"""add matrix.buildtype field

Revision ID: 356322f62cf2
Revises: e2d128239fef
Create Date: 2025-11-04 12:00:37.902156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356322f62cf2'
down_revision: Union[str, None] = 'e2d128239fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrices', sa.Column('build_type', sa.Enum('BINARY', 'TRINARY', name='matrixbuildtype'), nullable=True))
    op.create_index(op.f('ix_matrices_build_type'), 'matrices', ['build_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matrices_build_type'), table_name='matrices')
    op.drop_column('matrices', 'build_type')
    # ### end Alembic commands ###
