"""add_is_banned_field_to_telegram_user

Revision ID: 7a6f609b63f0
Revises: 803a290d9f1e
Create Date: 2025-10-08 13:05:50.981582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6f609b63f0'
down_revision: Union[str, None] = '803a290d9f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('is_banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'is_banned')
    # ### end Alembic commands ###
