"""add_depth_level_to_telegram_user

Revision ID: 803a290d9f1e
Revises: c09f2a13fdcb
Create Date: 2025-10-04 11:53:17.346929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803a290d9f1e'
down_revision: Union[str, None] = 'c09f2a13fdcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('depth_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'depth_level')
    # ### end Alembic commands ###
