"""add_is_canceled_field_to_donatinos

Revision ID: c09f2a13fdcb
Revises: 9c101da459b0
Create Date: 2025-09-22 06:59:21.436397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09f2a13fdcb'
down_revision: Union[str, None] = '9c101da459b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donate_transactions', sa.Column('is_canceled', sa.Boolean(), nullable=True))
    op.add_column('donates', sa.Column('is_canceled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donates', 'is_canceled')
    op.drop_column('donate_transactions', 'is_canceled')
    # ### end Alembic commands ###
