"""add binary_bill

Revision ID: d3edf73ad9d4
Revises: ae7a3c9ac3df
Create Date: 2025-11-08 12:31:41.178628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3edf73ad9d4'
down_revision: Union[str, None] = 'ae7a3c9ac3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('binary_bill', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'binary_bill')
    # ### end Alembic commands ###
