"""add telegram_user.binary_status field

Revision ID: d96ef217345c
Revises: 52538eb869b7
Create Date: 2025-11-04 14:50:13.850852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96ef217345c'
down_revision: Union[str, None] = '52538eb869b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('binary_status', sa.Enum('NOT_ACTIVE', 'BASE', 'BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'DIAMOND', 'BRILLIANT', name='donatestatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_users', 'binary_status')
    # ### end Alembic commands ###
