"""add donate.matrix_build_type field

Revision ID: f01044691b10
Revises: d96ef217345c
Create Date: 2025-11-05 11:02:02.221383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01044691b10'
down_revision: Union[str, None] = 'd96ef217345c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donates', sa.Column('matrix_build_type', sa.Enum('BINARY', 'TRINARY', name='matrixbuildtype'), nullable=True))
    op.create_index(op.f('ix_donates_matrix_build_type'), 'donates', ['matrix_build_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donates_matrix_build_type'), table_name='donates')
    op.drop_column('donates', 'matrix_build_type')
    # ### end Alembic commands ###
